// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAF.Data;

#nullable disable

namespace SAF.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260725032427_AgregarRowVersionParaConcurrencia")]
    partial class AgregarRowVersionParaConcurrencia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAF.Data.Entities.Devengado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Empresa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("empresa");

                    b.Property<string>("Expediente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("expediente");

                    b.Property<DateTime>("FechaImportacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_importacion");

                    b.Property<DateTime?>("FechaImputacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_imputacion");

                    b.Property<decimal?>("ImportePp")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe_pp");

                    b.Property<int>("NroDev")
                        .HasColumnType("int")
                        .HasColumnName("nro_dev");

                    b.Property<string>("TipoDev")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("tipo_dev");

                    b.HasKey("Id");

                    b.HasIndex("FechaImputacion");

                    b.HasIndex("TipoDev", "NroDev");

                    b.ToTable("Devengados");
                });

            modelBuilder.Entity("SAF.Data.Entities.DevengadoExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("CafSiNo")
                        .HasColumnType("bit")
                        .HasColumnName("caf_si_no");

                    b.Property<string>("Ccoo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ccoo");

                    b.Property<int>("DevengadoId")
                        .HasColumnType("int")
                        .HasColumnName("devengado_id");

                    b.Property<DateTime?>("FechaCcoo")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_ccoo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaFirmaOp")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_firma_op");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime?>("FechaNotificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_notificacion");

                    b.Property<int>("NroDev")
                        .HasColumnType("int")
                        .HasColumnName("nro_dev");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observaciones");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int?>("StatusDgayfOpcionId")
                        .HasColumnType("int")
                        .HasColumnName("status_dgayf_opcion_id");

                    b.Property<int?>("StatusOpOpcionId")
                        .HasColumnType("int")
                        .HasColumnName("status_op_opcion_id");

                    b.Property<string>("TipoDev")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("tipo_dev");

                    b.HasKey("Id");

                    b.HasIndex("DevengadoId")
                        .IsUnique();

                    b.HasIndex("StatusDgayfOpcionId");

                    b.HasIndex("StatusOpOpcionId");

                    b.HasIndex("TipoDev", "NroDev");

                    b.ToTable("DevengadosExtra");
                });

            modelBuilder.Entity("SAF.Data.Entities.ExpedienteCaf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<string>("Beneficiario")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("beneficiario");

                    b.Property<DateTime?>("Cargado")
                        .HasColumnType("datetime2")
                        .HasColumnName("cargado");

                    b.Property<string>("CcPagadora")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cc_pagadora");

                    b.Property<string>("Cuenta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cuenta");

                    b.Property<string>("Expediente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("expediente");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_pago");

                    b.Property<decimal?>("Iibb")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("iibb");

                    b.Property<decimal?>("ImporteNeto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe_neto");

                    b.Property<string>("Op")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("op");

                    b.Property<string>("Pase")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("pase");

                    b.Property<DateTime?>("Revisado")
                        .HasColumnType("datetime2")
                        .HasColumnName("revisado");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasKey("Id");

                    b.HasIndex("Anio");

                    b.HasIndex("Expediente");

                    b.ToTable("ExpedientesCaf");
                });

            modelBuilder.Entity("SAF.Data.Entities.ExpedienteSeguro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beneficiario")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("beneficiario");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("estado");

                    b.Property<string>("Expediente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("expediente");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_modificacion");

                    b.Property<decimal?>("ImporteNeto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe_neto");

                    b.Property<string>("Op")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("op");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int?>("SeguroOpcionId")
                        .HasColumnType("int")
                        .HasColumnName("seguro_opcion_id");

                    b.HasKey("Id");

                    b.HasIndex("Expediente");

                    b.HasIndex("SeguroOpcionId");

                    b.ToTable("ExpedientesSeguro");
                });

            modelBuilder.Entity("SAF.Data.Entities.SeguroOpcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<bool>("EsOk")
                        .HasColumnType("bit")
                        .HasColumnName("es_ok");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.ToTable("SeguroOpciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            EsOk = true,
                            Nombre = "ok",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            EsOk = true,
                            Nombre = "CAF/ok",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            EsOk = false,
                            Nombre = "Pendiente",
                            Orden = 3
                        });
                });

            modelBuilder.Entity("SAF.Data.Entities.StatusContabilidadExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("FaltaPoliza")
                        .HasColumnType("bit")
                        .HasColumnName("falta_poliza");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaIngresoFactura")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_ingreso_factura");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime?>("FechaPedidoFactura2")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_pedido_factura2");

                    b.Property<int>("NroDev")
                        .HasColumnType("int")
                        .HasColumnName("nro_dev");

                    b.Property<string>("ObservacionesCuentasPagar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observaciones_cuentas_pagar");

                    b.Property<string>("ObservacionesLiquidaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observaciones_liquidaciones");

                    b.Property<DateTime?>("ReiterarPedidoFactura3")
                        .HasColumnType("datetime2")
                        .HasColumnName("reiterar_pedido_factura3");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("SinFacturaMotivo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sin_factura_motivo");

                    b.Property<int?>("StatusContableOpcionId")
                        .HasColumnType("int")
                        .HasColumnName("status_contable_opcion_id");

                    b.Property<string>("TipoDev")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("tipo_dev");

                    b.Property<int?>("TramitadorCuentasPagarOpcionId")
                        .HasColumnType("int")
                        .HasColumnName("tramitador_cuentas_pagar_opcion_id");

                    b.Property<int?>("TramitadorLiquidacionesOpcionId")
                        .HasColumnType("int")
                        .HasColumnName("tramitador_liquidaciones_opcion_id");

                    b.HasKey("Id");

                    b.HasIndex("StatusContableOpcionId");

                    b.HasIndex("TramitadorCuentasPagarOpcionId");

                    b.HasIndex("TramitadorLiquidacionesOpcionId");

                    b.HasIndex("TipoDev", "NroDev")
                        .IsUnique();

                    b.ToTable("StatusContabilidadExtras");
                });

            modelBuilder.Entity("SAF.Data.Entities.StatusContableOpcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.ToTable("StatusContableOpciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Factura Pedida",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = false,
                            Nombre = "Frenar",
                            Orden = 23
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Liquidaciones",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "OP Lista",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Presupuesto",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "Problema SIGAF",
                            Orden = 6
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Nombre = "Seguros",
                            Orden = 7
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Nombre = "Falta Poliza",
                            Orden = 2
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Nombre = "Error en la Factura",
                            Orden = 8
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Nombre = "Error en Documentación",
                            Orden = 9
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Nombre = "No presenta factura",
                            Orden = 10
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Nombre = "Activo Fijo",
                            Orden = 11
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Nombre = "Para pedir FC",
                            Orden = 12
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Nombre = "Fuera de financiera",
                            Orden = 13
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Nombre = "No presenta factura - Envío de CCOO",
                            Orden = 14
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            Nombre = "Notificación cédula proveedor",
                            Orden = 15
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            Nombre = "Guarda temporal- No presenta Factura",
                            Orden = 16
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            Nombre = "DG Financiera",
                            Orden = 17
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            Nombre = "Archivado",
                            Orden = 18
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            Nombre = "Pendiente",
                            Orden = 19
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            Nombre = "Anulado",
                            Orden = 20
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            Nombre = "Falta Anexo I Banco",
                            Orden = 21
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            Nombre = "No presenta anexo I",
                            Orden = 22
                        });
                });

            modelBuilder.Entity("SAF.Data.Entities.StatusDgayfOpcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.ToTable("StatusDgayfOpciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "avanzar",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "avanzar CAF",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "no avanzar",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "no avanzar CAF",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "anulado",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "fuera financiera",
                            Orden = 6
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Nombre = "en proceso baja",
                            Orden = 7
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Nombre = "CCOO inf al area",
                            Orden = 8
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Nombre = "para desafectar",
                            Orden = 9
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Nombre = "GUARDA TEMPORAL",
                            Orden = 10
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Nombre = "Proceso Reclamo",
                            Orden = 11
                        });
                });

            modelBuilder.Entity("SAF.Data.Entities.StatusOpOpcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.ToTable("StatusOpOpciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "anulado",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "OP Firmada",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Pasado al pago BONO",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "pagado 2023",
                            Orden = 4
                        });
                });

            modelBuilder.Entity("SAF.Data.Entities.TramitadorCuentasPagarOpcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.ToTable("TramitadoresCuentasPagar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Daniela",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Verónica",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Mariela",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Ignacio",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Brian",
                            Orden = 5
                        });
                });

            modelBuilder.Entity("SAF.Data.Entities.TramitadorLiquidacionesOpcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.ToTable("TramitadoresLiquidaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Mayra",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Stephanie",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Camila",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Gabriel",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Mauro",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "Tadeo",
                            Orden = 6
                        });
                });

            modelBuilder.Entity("SAF.Data.Entities.DevengadoExtra", b =>
                {
                    b.HasOne("SAF.Data.Entities.Devengado", "Devengado")
                        .WithMany()
                        .HasForeignKey("DevengadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAF.Data.Entities.StatusDgayfOpcion", "StatusDgayfOpcion")
                        .WithMany()
                        .HasForeignKey("StatusDgayfOpcionId");

                    b.HasOne("SAF.Data.Entities.StatusOpOpcion", "StatusOpOpcion")
                        .WithMany()
                        .HasForeignKey("StatusOpOpcionId");

                    b.Navigation("Devengado");

                    b.Navigation("StatusDgayfOpcion");

                    b.Navigation("StatusOpOpcion");
                });

            modelBuilder.Entity("SAF.Data.Entities.ExpedienteSeguro", b =>
                {
                    b.HasOne("SAF.Data.Entities.SeguroOpcion", "SeguroOpcion")
                        .WithMany()
                        .HasForeignKey("SeguroOpcionId");

                    b.Navigation("SeguroOpcion");
                });

            modelBuilder.Entity("SAF.Data.Entities.StatusContabilidadExtra", b =>
                {
                    b.HasOne("SAF.Data.Entities.StatusContableOpcion", "StatusContableOpcion")
                        .WithMany()
                        .HasForeignKey("StatusContableOpcionId");

                    b.HasOne("SAF.Data.Entities.TramitadorCuentasPagarOpcion", "TramitadorCuentasPagarOpcion")
                        .WithMany()
                        .HasForeignKey("TramitadorCuentasPagarOpcionId");

                    b.HasOne("SAF.Data.Entities.TramitadorLiquidacionesOpcion", "TramitadorLiquidacionesOpcion")
                        .WithMany()
                        .HasForeignKey("TramitadorLiquidacionesOpcionId");

                    b.Navigation("StatusContableOpcion");

                    b.Navigation("TramitadorCuentasPagarOpcion");

                    b.Navigation("TramitadorLiquidacionesOpcion");
                });
#pragma warning restore 612, 618
        }
    }
}
