// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAF.Data;

#nullable disable

namespace SAF.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703191314_AddExpedienteCafYDeriveFechaPagoCaf")]
    partial class AddExpedienteCafYDeriveFechaPagoCaf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAF.Data.Entities.Devengado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Empresa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("empresa");

                    b.Property<string>("Expediente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("expediente");

                    b.Property<DateTime>("FechaImportacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_importacion");

                    b.Property<DateTime?>("FechaImputacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_imputacion");

                    b.Property<decimal?>("ImportePp")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe_pp");

                    b.Property<int>("NroDev")
                        .HasColumnType("int")
                        .HasColumnName("nro_dev");

                    b.Property<string>("TipoDev")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("tipo_dev");

                    b.HasKey("Id");

                    b.HasIndex("FechaImputacion");

                    b.HasIndex("TipoDev", "NroDev");

                    b.ToTable("Devengados");
                });

            modelBuilder.Entity("SAF.Data.Entities.DevengadoExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuzonSade")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("buzon_sade");

                    b.Property<bool?>("CafSiNo")
                        .HasColumnType("bit")
                        .HasColumnName("caf_si_no");

                    b.Property<string>("Ccoo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ccoo");

                    b.Property<DateTime?>("FechaCcoo")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_ccoo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaFirmaOp")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_firma_op");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime?>("FechaNotificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_notificacion");

                    b.Property<DateTime?>("FechaSade")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_sade");

                    b.Property<int>("NroDev")
                        .HasColumnType("int")
                        .HasColumnName("nro_dev");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observaciones");

                    b.Property<string>("SegurosTeso")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("seguros_teso");

                    b.Property<int?>("StatusDgayfOpcionId")
                        .HasColumnType("int")
                        .HasColumnName("status_dgayf_opcion_id");

                    b.Property<int?>("StatusOpOpcionId")
                        .HasColumnType("int")
                        .HasColumnName("status_op_opcion_id");

                    b.Property<string>("TipoDev")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("tipo_dev");

                    b.HasKey("Id");

                    b.HasIndex("StatusDgayfOpcionId");

                    b.HasIndex("StatusOpOpcionId");

                    b.HasIndex("TipoDev", "NroDev")
                        .IsUnique();

                    b.ToTable("DevengadosExtra");
                });

            modelBuilder.Entity("SAF.Data.Entities.ExpedienteCaf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<string>("Beneficiario")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("beneficiario");

                    b.Property<DateTime?>("Cargado")
                        .HasColumnType("datetime2")
                        .HasColumnName("cargado");

                    b.Property<string>("CcPagadora")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cc_pagadora");

                    b.Property<string>("Cuenta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cuenta");

                    b.Property<string>("Expediente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("expediente");

                    b.Property<string>("ExpedienteFinanciera")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("expediente_financiera");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_pago");

                    b.Property<decimal?>("Iibb")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("iibb");

                    b.Property<decimal?>("ImporteNeto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe_neto");

                    b.Property<string>("Op")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("op");

                    b.Property<string>("Pase")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("pase");

                    b.Property<DateTime?>("Revisado")
                        .HasColumnType("datetime2")
                        .HasColumnName("revisado");

                    b.HasKey("Id");

                    b.HasIndex("Anio");

                    b.HasIndex("ExpedienteFinanciera");

                    b.ToTable("ExpedientesCaf");
                });

            modelBuilder.Entity("SAF.Data.Entities.StatusContabilidadExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("FaltaPoliza")
                        .HasColumnType("bit")
                        .HasColumnName("falta_poliza");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaIngresoFactura")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_ingreso_factura");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime?>("FechaPedidoFactura2")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_pedido_factura2");

                    b.Property<int>("NroDev")
                        .HasColumnType("int")
                        .HasColumnName("nro_dev");

                    b.Property<string>("ObservacionesCuentasPagar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observaciones_cuentas_pagar");

                    b.Property<string>("ObservacionesLiquidaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observaciones_liquidaciones");

                    b.Property<DateTime?>("ReiterarPedidoFactura3")
                        .HasColumnType("datetime2")
                        .HasColumnName("reiterar_pedido_factura3");

                    b.Property<int?>("StatusContableOpcionId")
                        .HasColumnType("int")
                        .HasColumnName("status_contable_opcion_id");

                    b.Property<string>("TipoDev")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("tipo_dev");

                    b.Property<int?>("TramitadorCuentasPagarOpcionId")
                        .HasColumnType("int")
                        .HasColumnName("tramitador_cuentas_pagar_opcion_id");

                    b.Property<int?>("TramitadorLiquidacionesOpcionId")
                        .HasColumnType("int")
                        .HasColumnName("tramitador_liquidaciones_opcion_id");

                    b.Property<string>("UltimoMovimientoSade")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ultimo_movimiento_sade");

                    b.HasKey("Id");

                    b.HasIndex("StatusContableOpcionId");

                    b.HasIndex("TramitadorCuentasPagarOpcionId");

                    b.HasIndex("TramitadorLiquidacionesOpcionId");

                    b.HasIndex("TipoDev", "NroDev")
                        .IsUnique();

                    b.ToTable("StatusContabilidadExtras");
                });

            modelBuilder.Entity("SAF.Data.Entities.StatusContableOpcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.ToTable("StatusContableOpciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Factura Pedida",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Frenar",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Liquidaciones",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "OP Lista",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Presupuesto",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "Problema SIGAF",
                            Orden = 6
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Nombre = "Seguros",
                            Orden = 7
                        });
                });

            modelBuilder.Entity("SAF.Data.Entities.StatusDgayfOpcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.ToTable("StatusDgayfOpciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "avanzar",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "avanzar CAF",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "no avanzar",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "no avanzar CAF",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "anulado",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "fuera financiera",
                            Orden = 6
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Nombre = "en proceso baja",
                            Orden = 7
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Nombre = "CCOO inf al area",
                            Orden = 8
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Nombre = "para desafectar",
                            Orden = 9
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Nombre = "GUARDA TEMPORAL",
                            Orden = 10
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Nombre = "Proceso Reclamo",
                            Orden = 11
                        });
                });

            modelBuilder.Entity("SAF.Data.Entities.StatusOpOpcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.ToTable("StatusOpOpciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "anulado",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "OP Firmada",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Pasado al pago BONO",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "pagado 2023",
                            Orden = 4
                        });
                });

            modelBuilder.Entity("SAF.Data.Entities.TramitadorCuentasPagarOpcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.ToTable("TramitadoresCuentasPagar");
                });

            modelBuilder.Entity("SAF.Data.Entities.TramitadorLiquidacionesOpcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.ToTable("TramitadoresLiquidaciones");
                });

            modelBuilder.Entity("SAF.Data.Entities.DevengadoExtra", b =>
                {
                    b.HasOne("SAF.Data.Entities.StatusDgayfOpcion", "StatusDgayfOpcion")
                        .WithMany()
                        .HasForeignKey("StatusDgayfOpcionId");

                    b.HasOne("SAF.Data.Entities.StatusOpOpcion", "StatusOpOpcion")
                        .WithMany()
                        .HasForeignKey("StatusOpOpcionId");

                    b.Navigation("StatusDgayfOpcion");

                    b.Navigation("StatusOpOpcion");
                });

            modelBuilder.Entity("SAF.Data.Entities.StatusContabilidadExtra", b =>
                {
                    b.HasOne("SAF.Data.Entities.StatusContableOpcion", "StatusContableOpcion")
                        .WithMany()
                        .HasForeignKey("StatusContableOpcionId");

                    b.HasOne("SAF.Data.Entities.TramitadorCuentasPagarOpcion", "TramitadorCuentasPagarOpcion")
                        .WithMany()
                        .HasForeignKey("TramitadorCuentasPagarOpcionId");

                    b.HasOne("SAF.Data.Entities.TramitadorLiquidacionesOpcion", "TramitadorLiquidacionesOpcion")
                        .WithMany()
                        .HasForeignKey("TramitadorLiquidacionesOpcionId");

                    b.Navigation("StatusContableOpcion");

                    b.Navigation("TramitadorCuentasPagarOpcion");

                    b.Navigation("TramitadorLiquidacionesOpcion");
                });
#pragma warning restore 612, 618
        }
    }
}
